# Settings for Bolt Article

# All options: blockcode, buttonlink, carousel, clips, counter, definedlinks,
# filelink, handle, icons, imageposition, imageresize, inlineformat, makebutton,
# math, print, removeformat, reorder, selector, slideshow, specialchars, style,
# tags, textdirection, underline, variable
default:
  plugins: [ blockcode, buttonlink, definedlinks, inlineformat, reorder, tags, underline, imageposition, filelink, removeformat, imageresize ]
  source: true
  grid:
    classname: 'article-grid'
    columns: 12
    patterns:
      '4|4|4': 'col-4|col-4|col-4'
      '4|8': 'col-4|col-8'
      '6|6': 'col-6|col-6'
      '8|4': 'col-8|col-4'

  # Settings for images
  # Note: The current editor can only upload / insert images if they are granted 
  # the 'upload' and 'list_files:files' permissions in `permissions.yaml`.  
  image:
    thumbnail: 1000×1000×max

plugins:
  ~
